(load-library "required-packages")
(load-library "set-variables")
(load-library "define-functions")
(load-library "rotate-files")
(load-library "keyboard-shortcuts")
(load-library "hooks")
;; (load-library "git-timemachine")

(load "server")
(unless (server-running-p) (server-start))
