#!/bin/bash

PWD=`pwd`
NAME=`basename $PWD`

source ~/.bashrc

echo "penv $NAME"
penv $NAME

set -Eeuxo pipefail

# GRRR!
# /Users/tom/.virtualenvs/util/bin/black -l 79 -S .
/Users/tom/.virtualenvs/util/bin/simp -x

flake8 *.py
pytest $@
