#!/bin/bash

PWD=`pwd`
NAME=`basename $PWD`

source ~/.bashrc

echo "penv $NAME"
penv $NAME

set -Eeuxo pipefail
pytest $@

# /Users/tom/.virtualenvs/util/bin/black -l 79 -S .
flake8
# /Users/tom/.virtualenvs/util/bin/simp
